# Notebook 04 - Feature Engineering

## Objective

The objective of this notebook is to engineer new features from the cleaned football dataset. These features will provide additional insights into player performance and will be used for:

- SQL Analysis
- Power BI Dashboard
- Machine Learning (Player Clustering)

Rather than relying only on raw statistics such as goals and assists, feature engineering helps create more meaningful performance indicators.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/players_data_cleaned.csv")

df.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,MP,Starts,...,Att (GK),Thr,Launch%,AvgLen,Opp,Stp,Stp%,#OPA,#OPA/90,AvgDist
0,1,Max Aarons,eng ENG,DF,Bournemouth,eng Premier League,24.0,2000.0,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Max Aarons,eng ENG,"DF,MF",Valencia,es La Liga,24.0,2000.0,4,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Rodrigo Abajas,es ESP,DF,Valencia,es La Liga,21.0,2003.0,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,James Abankwah,ie IRL,"DF,MF",Udinese,it Serie A,20.0,2004.0,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,18.0,2006.0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.shape

(2846, 165)

## Creating New Features

The original dataset contains many useful statistics. However, we can derive additional metrics that better represent player performance.

These engineered features will be used throughout the remainder of the project.

## Feature 1 – Goal Difference

### Definition

Goal Difference measures the difference between the number of goals a player scored and their Expected Goals (xG).

### Formula

Goal Difference = Goals − Expected Goals (xG)

### Why it matters

Players with a positive Goal Difference have scored more goals than expected, indicating efficient finishing. Conversely, a negative value suggests that a player scored fewer goals than expected.

In [4]:
df["Goal_Difference"] = df["Gls"] - df["xG"]

df[["Player", "Gls", "xG", "Goal_Difference"]].head()

C:\Users\aksha\AppData\Local\Temp\ipykernel_19656\3682274493.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Goal_Difference"] = df["Gls"] - df["xG"]

              Player  Gls   xG  Goal_Difference
0         Max Aarons    0  0.0              0.0
1         Max Aarons    0  0.0              0.0
2     Rodrigo Abajas    0  0.1             -0.1
3     James Abankwah    0  0.1             -0.1
4  Keyliane Abdallah    0  0.0              0.0

### Result

A new feature named **Goal_Difference** has been successfully created. This metric will be used later to identify players who outperform or underperform their expected goal values.

## Feature 2 – Goal Contributions

### Definition

Goal Contributions represent the total number of goals and assists recorded by a player.

### Formula

Goal Contributions = Goals + Assists

### Why it matters

Some players contribute by scoring goals, while others contribute by creating chances for teammates. Goal Contributions combines both aspects into a single attacking metric, making it useful for comparing overall offensive impact.

In [5]:
df["Goal_Contributions"] = df["Gls"] + df["Ast"]

df[["Player", "Gls", "Ast", "Goal_Contributions"]].head()

C:\Users\aksha\AppData\Local\Temp\ipykernel_19656\2024974475.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Goal_Contributions"] = df["Gls"] + df["Ast"]

              Player  Gls  Ast  Goal_Contributions
0         Max Aarons    0    0                   0
1         Max Aarons    0    0                   0
2     Rodrigo Abajas    0    0                   0
3     James Abankwah    0    0                   0
4  Keyliane Abdallah    0    0                   0

Some Other Players

In [6]:
df.sort_values("Goal_Contributions", ascending=False)[
    ["Player", "Gls", "Ast", "Goal_Contributions"]
].head(10)

                  Player  Gls  Ast  Goal_Contributions
2296       Mohamed Salah   29   18                  47
1313          Harry Kane   26    9                  35
1685       Kylian Mbappé   31    3                  34
2193       Mateo Retegui   25    8                  33
1215      Alexander Isak   23    6                  29
1479  Robert Lewandowski   27    2                  29
694      Ousmane Dembélé   21    6                  27
2169            Raphinha   18    9                  27
1687        Bryan Mbeumo   20    7                  27
1952       Michael Olise   12   15                  27

### Result

A new feature named **Goal_Contributions** has been created. This metric measures a player's overall attacking output by combining goals and assists into a single statistic.

## Feature 3 – Goals per 90 Minutes

### Definition

Goals per 90 Minutes estimates how many goals a player scores during a full 90-minute match.

### Formula

Goals per 90 = (Goals / Minutes Played) × 90

### Why it matters

Total goals alone can be misleading because players receive different amounts of playing time. Goals per 90 provides a fair comparison by standardizing performance over a full match.

In [10]:
df["Goals_per90"] = ((df["Gls"] / df["Min"]) * 90).round(2)

df[["Player", "Gls", "Min", "Goals_per90"]].sample(10)

                Player  Gls   Min  Goals_per90
847      Patrick Erras    1   832         0.11
1851       Pau Navarro    0   916         0.00
800       Paulo Dybala    6  1417         0.38
1108        Robin Hack    4  2172         0.17
1144     Mario Hermoso    0   293         0.00
803        Aron Dønnum    2  2689         0.07
898       Jordan Ferri    0  1773         0.00
2581  Adrien Thomasson    3  2615         0.10
2309  Mama Samba Baldé    2  1149         0.16
1197     Stanis Idumbo    1   284         0.32

### Result

A new feature named **Goals_per90** has been created. This metric standardizes goal-scoring performance based on playing time, making it possible to compare players fairly regardless of the number of minutes they have played.

In [11]:
df_filtered = df[df["Min"] >= 900]

## Feature 4 – Assists per 90 Minutes

### Definition

Assists per 90 Minutes estimates how many assists a player provides during a full 90-minute match.

### Formula

Assists per 90 = (Assists / Minutes Played) × 90

### Why it matters

Total assists do not account for differences in playing time. Assists per 90 provides a standardized measure of creativity, allowing fair comparisons between players who have played different numbers of minutes.

In [12]:
df["Assists_per90"] = ((df["Ast"] / df["Min"]) * 90).round(2)

df[["Player", "Ast", "Min", "Assists_per90"]].sample(10)

C:\Users\aksha\AppData\Local\Temp\ipykernel_19656\456357330.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Assists_per90"] = ((df["Ast"] / df["Min"]) * 90).round(2)

                     Player  Ast   Min  Assists_per90
1971            Loïs Openda    5  2453           0.18
1519            Iker Losada    0   358           0.00
2371          Marvin Schulz    0   306           0.00
380          Darko Brašanac    2  1617           0.11
1368  Magnus Kofod Andersen    1   695           0.13
1830     Kingstone Mutandwa    0   127           0.00
214         Alejandro Balde    4  2284           0.16
2420            Xavi Simons    6  2150           0.25
207          Mitchel Bakker    0    22           0.00
1582          Youssef Maleh    1  1510           0.06

### Result

A new feature named **Assists_per90** has been created. This metric measures a player's creative contribution on a per-match basis, making it easier to compare players with different amounts of playing time.

## Feature 5 – Goal Contributions per 90 Minutes

### Definition

Goal Contributions per 90 Minutes measures the average number of goals and assists a player contributes during a full 90-minute match.

### Formula

Goal Contributions per 90 = (Goal Contributions / Minutes Played) × 90

### Why it matters

This metric combines both goal scoring and chance creation into a single standardized measure. It provides a fair comparison between players regardless of playing time.

In [13]:
df["GC_per90"] = (
    (df["Goal_Contributions"] / df["Min"]) * 90
).round(2)

df[
    [
        "Player",
        "Goal_Contributions",
        "Min",
        "GC_per90"
    ]
].sample(10)

C:\Users\aksha\AppData\Local\Temp\ipykernel_19656\2028762359.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["GC_per90"] = (

                  Player  Goal_Contributions   Min  GC_per90
2444       Naatan Skyttä                   0     5      0.00
1725          Karol Mets                   0   900      0.00
1294  Christian Kabasele                   2  1161      0.16
974         James Garner                   1  1594      0.06
1983   Riccardo Orsolini                  19  1878      0.91
139      Aritz Arambarri                   0   177      0.00
2832        Melvin Zinga                   0    90      0.00
2074     Andreas Pereira                   6  2013      0.27
1535          Saša Lukić                   2  2344      0.08
853              Estanis                   0     9      0.00

### Result

A new feature named **GC_per90** has been created. This metric represents a player's total attacking contribution per full match and combines both goals and assists into a single standardized performance indicator.

## Feature 6 – Finishing Efficiency

### Definition

Finishing Efficiency measures how effectively a player converts expected goals into actual goals.

### Formula

Finishing Efficiency = Goals / Expected Goals (xG)

### Why it matters

A value greater than 1 indicates that a player scored more goals than expected, suggesting highly efficient finishing. A value below 1 indicates that the player scored fewer goals than expected.

In [14]:
(df["xG"] == 0).sum()

np.int64(638)

In [15]:
df["Finishing_Efficiency"] = np.where(
    df["xG"] > 0,
    (df["Gls"] / df["xG"]).round(2),
    np.nan
)

df[
    [
        "Player",
        "Gls",
        "xG",
        "Finishing_Efficiency"
    ]
].sample(10)

C:\Users\aksha\AppData\Local\Temp\ipykernel_19656\1207250643.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["Finishing_Efficiency"] = np.where(

                     Player  Gls    xG  Finishing_Efficiency
405             Emi Buendía    2   0.9                  2.22
2775      Maximilian Wittek    0   1.4                  0.00
1045    Lucas Gourna-Douath    0   0.1                  0.00
695       Ermedin Demirović   15  14.1                  1.06
239          Nicolò Barella    3   2.2                  1.36
1855  Youssouf Ndayishimiye    3   0.9                  3.33
972             Unai García    0   0.0                   NaN
1689          Kasey McAteer    1   1.0                  1.00
1545          Mathias Løvik    0   0.1                  0.00
1342           Milos Kerkez    2   0.6                  3.33

### Result

A new feature named **Finishing_Efficiency** has been created. To avoid division by zero, players with an Expected Goals (xG) value of zero were assigned a missing value (`NaN`). This ensures the dataset remains suitable for further analysis, SQL queries, Power BI dashboards, and machine learning models.

## Final Dataset Validation

Before exporting the dataset, we verify that all newly engineered features have been created successfully and contain valid values.

In [16]:
new_features = [
    "Goal_Difference",
    "Goal_Contributions",
    "Goals_per90",
    "Assists_per90",
    "GC_per90",
    "Finishing_Efficiency"
]

df[new_features].describe()

,Goal_Difference,Goal_Contributions,Goals_per90,Assists_per90,GC_per90,Finishing_Efficiency
count,2846.000000,2846.000000,2846.000000,2846.000000,2846.000000,2208.000000
mean,-0.023472,2.890724,0.112017,0.076911,0.188949,0.858601
std,1.114315,4.534772,0.196349,0.136767,0.264615,1.123147
min,-6.600000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-0.400000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,0.000000,0.000000,0.080000,0.730000
75%,0.200000,4.000000,0.160000,0.120000,0.290000,1.250000
max,8.300000,47.000000,2.430000,2.650000,2.650000,10.000000

In [17]:
df[new_features].isnull().sum()

Goal_Difference           0
Goal_Contributions        0
Goals_per90               0
Assists_per90             0
GC_per90                  0
Finishing_Efficiency    638
dtype: int64

### Validation Summary

All engineered features were successfully created.

The only missing values are in the **Finishing_Efficiency** column, where players with an Expected Goals (xG) value of zero were intentionally assigned `NaN` to avoid division-by-zero errors.

In [18]:
df.to_csv("../data/processed/players_final.csv", index=False)

print("Final dataset saved successfully!")

Final dataset saved successfully!

In [19]:
import os

os.listdir("../data/processed")

['players_data_cleaned.csv', 'players_final.csv']

# Notebook Summary

In this notebook, several new performance metrics were engineered from the cleaned dataset.

The following features were created:

- Goal_Difference
- Goal_Contributions
- Goals_per90
- Assists_per90
- GC_per90
- Finishing_Efficiency

These engineered features provide a richer representation of player performance and will be used in the next stages of the project, including SQL analysis, Power BI dashboards, and machine learning.